### ISSUE TITLE
twee apare files droppen

### ISSUE THREAD

**Issue by Geraldhub** [NLADC/DDoS-Gameboard#39]
Quicklogging: Alle browsers, Windows en Mac 2 files tegelijk uploaden door te slepen

**Comment by AfroSjack** [comment]
Ik heb hier meer beschrijving nodig? welke Files Waar? Droppen?

**Comment by Geraldhub** [comment]
Moeten we vragen aan Jeroen, ik heb ook geen idee.

De huidige file drop werkt toch?

**Comment by AfroSjack** [comment]
ja
