### ISSUE TITLE
Afbeeldingen in de log ZIP toevoegen

### ISSUE THREAD

**Issue by Geraldhub** [NLADC/DDoS-Gameboard#68]

**Comment by AfroSjack** [comment]
Je kunt in de instellingen zip toevoegen als een geaccepteerde extensie, en dan neemt het systeem dit automatisch over.
![image](https://github.com/user-attachments/assets/4445353e-88cb-49d3-8562-41e5a429b0e2)
Dit is op de dev1 test omgeving nu, Heb Zip als standZaard geaccepteerde estensie toegevoegd. Dus als je helemaal niets als geaccepteerde extensie instelt zal die standaard werken.
